services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80" # Expone el puerto 80 del contenedor al 5173 de tu máquina
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: on-failure
    environment:
      - PORT=${BACKEND_PORT}
      - DB_HOST=db_mysql
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      db_mysql:
        condition: service_healthy

  db_mysql:
    image: mysql:8.0 
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:










#
#services:
#  backend:
#    build: ./backend
#    ports:
#      - "8080:8080"
#    # Esta política es una buena red de seguridad general.
#    restart: on-failure
#    environment:
#      - DB_HOST=db_mysql
#      - DB_PORT=3306
#      - DB_USER=user
#      - DB_PASSWORD=password
#      - DB_NAME=mortgage
#    depends_on:
#      db_mysql:
#        # Esto SOLUCIONA la condición de carrera del arranque.
#        condition: service_healthy
#
#  db_mysql:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root_password
#      - MYSQL_DATABASE=mortgage
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data: